### ISSUE TITLE
Error when doing multiple - but different - calls on one page

### ISSUE THREAD

**Issue by xiaohutai** [graham73may/bolt-related-content#2]
Just FYI.

I had related questions (`vragen`) and related `blog` items on a page:

```
{% set related = relatedcontent(record, {
    limit: 5,
    contenttypes : [ 'vragen' ]
}) %}
```

```
{% set related = relatedcontent(record, {
    limit: 2,
    contenttypes : [ 'blog' ]
}) %}
```

But the second `relatedcontent` query gave me both `vragen` and `blog` items.

**Comment by graham73may** [comment]
Interesting one! 

Does this also happen if for the blog one you used `{% set related_blogs = ...`

**Comment by xiaohutai** [comment]
It's not related to assignment. See below:

```
        {% set foo = relatedcontent(record, {
            limit: 5,
            contenttypes : [ 'vragen' ]
        }) %}
        {% set bar = relatedcontent(record, {
            limit: 2,
            contenttypes : [ 'blog' ]
        }) %}

        {% for i in foo %}
            {{ dump(i.contenttype.slug) }}
        {% endfor %}
        {% for j in bar %}
            {{ dump(j.contenttype.slug) }}
        {% endfor %}
```

In my case:
```
"vragen"
"vragen"
"vragen"
"vragen"
"vragen"

"blog"
"vragen" <-- wut
```

I believe there are values stored on the first call, and the second call gets an odd _side-effect_ of the first call. The first call is always clean/good.

**Comment by graham73may** [comment]
Ah sorry, you are completely right.

These need emptying inside getRelatedContent. 
```
    private $manual_results = [];
    private $weighted_results = [];
    private $auto_results = [];
```

**Comment by graham73may** [comment]
@xiaohutai 

Just pushed a fix for this, can you install the plugin from master (instead of a release) and let me know if it fixes the issue? 

https://github.com/graham73may/bolt-related-content/commit/9a64abe11117b86e6e9fad42e60135304073872a

If that puts everything in place I'll do a new release.

**Comment by xiaohutai** [comment]
Boom! That works for me! 👍

**Comment by graham73may** [comment]
Great I'll do a release now! :) thanks for the help.
